services:
  gateway:
    build:
      context: ./agent-app-fe
      dockerfile: Dockerfile
      target: execute
      args:
        API_URL: "http://localhost:8000/agent-app/api"
    image: evaj10/agent-app-front:${FRONT_VERSION:-latest}
    restart: on-failure
    networks:
      - agent-app-net
    ports:
      - "8000:8000"
    volumes:
      - ./agent-app-fe/nginx.conf:/etc/nginx/nginx.conf
      - ./agent-app-fe/gateway.conf:/etc/nginx/gateway.conf
    depends_on:
      - agent-app

  agent-app:
    build:
      context: ./agent-app
      dockerfile: Dockerfile
      target: ${TARGET:-appServerRuntime}
    image: evaj10/agent-app:${VERSION:-latest}
    restart: on-failure
    networks:
      - agent-app-net
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DOMAIN: ${DATABASE_DOMAIN}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      CORS_ORIGIN: ${CORS_ORIGIN}
      STAGE: ${STAGE}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    networks:
      - agent-app-net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      retries: 3
      interval: 5s
      timeout: 5s
    volumes:
      - database-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.3
    networks:
      - agent-app-net
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ROOT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ROOT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PUBLISHED_PORT-8081}:80"
    depends_on:
      - database

volumes:
  database-data:
    name: server-database
  pgadmin:
    name: pgadmin

networks:
  agent-app-net:
    name: agent-app-net
    driver: bridge
