export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";

export const GET_COMPANY_REQUESTS = "GET_COMPANY_REQUESTS";
export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const ACCEPT_COMPANY_REQUEST = "ACCEPT_COMPANY_REQUEST";
export const DECLINE_COMPANY_REQUEST = "DECLINE_COMPANY_REQUEST";

export const GET_COMPANIES = "GET_COMPANIES";
export const EDIT_COMPANY = "EDIT_COMPANY";
