export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";

export const ADD_API_KEY = "ADD_API_KEY";

export const GET_COMPANY_REQUESTS = "GET_COMPANY_REQUESTS";
export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const ACCEPT_COMPANY_REQUEST = "ACCEPT_COMPANY_REQUEST";
export const DECLINE_COMPANY_REQUEST = "DECLINE_COMPANY_REQUEST";

export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANY_BY_ID = "GET_COMPANY_BY_ID";
export const EDIT_COMPANY = "EDIT_COMPANY";

export const GET_COMPANY_JOB_OFFERS = "GET_COMPANY_JOB_OFFERS";
export const GET_COMPANY_COMMENTS = "GET_COMPANY_COMMENTS";
export const GET_COMPANY_INTERVIEWS = "GET_COMPANY_INTERVIEWS";
export const GET_COMPANY_SALARIES = "GET_COMPANY_SALARIES";

export const CREATE_COMPANY_JOB_OFFER = "CREATE_COMPANY_JOB_OFFER";
export const CREATE_COMPANY_COMMENT = "CREATE_COMPANY_COMMENT";
export const CREATE_COMPANY_INTERVIEW = "CREATE_COMPANY_INTERVIEW";
export const CREATE_COMPANY_SALARY = "CREATE_COMPANY_SALARY";
