name: SpringBoot-CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

env:
  PROJ_DIR: ./agent-app
  PROJ_DIR_FE: ./agent-app-fe
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/agent-app
  DOCKERHUB_REPO_FE: ${{ secrets.DOCKERHUB_USERNAME }}/agent-app-front

jobs:
  ci-pipe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test with Maven - BE
        run: mvn -B test --file ./agent-app/pom.xml

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: ${{ env.PROJ_DIR_FE }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Build with NPM - FE
        working-directory: ${{ env.PROJ_DIR_FE }}
        run: |
          npm ci
          npm run build --if-present

      - name: Create a Release
        id: version
        if: github.event_name == 'push'
        run: |
          npm install semantic-release
          npm install semantic-release-export-data
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages to GPR
        if: github.event_name == 'push'
        run: |
          mvn --file ./agent-app/pom.xml --batch-mode deploy -DskipTests -Drevision=${{ steps.version.outputs.new-release-version }}
          cd ${{ env.PROJ_DIR_FE }}
          npm version ${{ steps.version.outputs.new-release-version }}
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build BE image and push to Docker Hub
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.PROJ_DIR }}
          tags: ${{ format('{0}:{1}', env.DOCKERHUB_REPO, steps.version.outputs.new-release-version) }}, ${{ secrets.DOCKERHUB_REPO }}:latest
          push: true
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:buildcache,mode=max
      - name: Build FE image and push to Docker Hub
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.PROJ_DIR_FE }}
          tags: ${{ format('{0}:{1}', env.DOCKERHUB_REPO_FE, steps.version.outputs.new-release-version) }}, ${{ secrets.DOCKERHUB_REPO_FE }}:latest
          push: true
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO_FE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO_FE }}:buildcache,mode=max

      - name: Deploy app to TEST env
        if: github.event_name == 'push' && github.ref_name == 'develop'
        run: |
          cd agent-app/deployment
          export TERRAFORM_BACKEND=agent-app-backend-test
          export APP_NAME=dislinkt-agent-app-test
          export GATEWAY_NAME=agent-app-frontend-test
          export HEROKU_EMAIL=${{ secrets.HEROKU_TEST_EMAIL }}
          export HEROKU_API_KEY=${{ secrets.HEROKU_TEST_API_KEY }}
          docker compose up destroy
          docker compose up deploy
      
      - name: Deploy app to PROD env
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          cd agent-app/deployment
          export HEROKU_EMAIL=${{ secrets.HEROKU_PROD_EMAIL }}
          export HEROKU_API_KEY=${{ secrets.HEROKU_PROD_API_KEY }}
          docker compose up destroy
          docker compose up deploy
      
